<?php

namespace Database\Seeders;

use App\Models\Canton;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
         Canton::insert([
            ['id' => 1, 'provincia_id' => 1, 'codigo' => '0101', 'nombre' => 'CUENCA'],
            ['id' => 2, 'provincia_id' => 1, 'codigo' => '0102', 'nombre' => 'GIRÓN'],
            ['id' => 3, 'provincia_id' => 1, 'codigo' => '0103', 'nombre' => 'GUALACEO'],
            ['id' => 4, 'provincia_id' => 1, 'codigo' => '0104', 'nombre' => 'NABÓN'],
            ['id' => 5, 'provincia_id' => 1, 'codigo' => '0105', 'nombre' => 'PAUTE'],
            ['id' => 6, 'provincia_id' => 1, 'codigo' => '0106', 'nombre' => 'PUCARÁ'],
            ['id' => 7, 'provincia_id' => 1, 'codigo' => '0107', 'nombre' => 'SAN FERNANDO'],
            ['id' => 8, 'provincia_id' => 1, 'codigo' => '0108', 'nombre' => 'SANTA ISABEL'],
            ['id' => 9, 'provincia_id' => 1, 'codigo' => '0109', 'nombre' => 'SÍGSIG'],
            ['id' => 10, 'provincia_id' => 1, 'codigo' => '0110', 'nombre' => 'OÑA'],
            ['id' => 11, 'provincia_id' => 1, 'codigo' => '0111', 'nombre' => 'CHORDELEG'],
            ['id' => 12, 'provincia_id' => 1, 'codigo' => '0112', 'nombre' => 'EL PAN'],
            ['id' => 13, 'provincia_id' => 1, 'codigo' => '0113', 'nombre' => 'SEVILLA DE ORO'],
            ['id' => 14, 'provincia_id' => 1, 'codigo' => '0114', 'nombre' => 'GUACHAPALA'],
            ['id' => 15, 'provincia_id' => 1, 'codigo' => '0115', 'nombre' => 'CAMILO PONCE ENRÍQUEZ'],
            ['id' => 16, 'provincia_id' => 2, 'codigo' => '0201', 'nombre' => 'GUARANDA'],
            ['id' => 17, 'provincia_id' => 2, 'codigo' => '0202', 'nombre' => 'CHILLANES'],
            ['id' => 18, 'provincia_id' => 2, 'codigo' => '0203', 'nombre' => 'CHIMBO'],
            ['id' => 19, 'provincia_id' => 2, 'codigo' => '0204', 'nombre' => 'ECHEANDÍA'],
            ['id' => 20, 'provincia_id' => 2, 'codigo' => '0205', 'nombre' => 'SAN MIGUEL'],
            ['id' => 21, 'provincia_id' => 2, 'codigo' => '0206', 'nombre' => 'CALUMA'],
            ['id' => 22, 'provincia_id' => 2, 'codigo' => '0207', 'nombre' => 'LAS NAVES'],
            ['id' => 23, 'provincia_id' => 3, 'codigo' => '0301', 'nombre' => 'AZOGUES'],
            ['id' => 24, 'provincia_id' => 3, 'codigo' => '0302', 'nombre' => 'BIBLIÁN'],
            ['id' => 25, 'provincia_id' => 3, 'codigo' => '0303', 'nombre' => 'CAÑAR'],
            ['id' => 26, 'provincia_id' => 3, 'codigo' => '0304', 'nombre' => 'LA TRONCAL'],
            ['id' => 27, 'provincia_id' => 3, 'codigo' => '0305', 'nombre' => 'EL TAMBO'],
            ['id' => 28, 'provincia_id' => 3, 'codigo' => '0306', 'nombre' => 'DÉLEG'],
            ['id' => 29, 'provincia_id' => 3, 'codigo' => '0307', 'nombre' => 'SUSCAL'],
            ['id' => 30, 'provincia_id' => 4, 'codigo' => '0401', 'nombre' => 'TULCÁN'],
            ['id' => 31, 'provincia_id' => 4, 'codigo' => '0402', 'nombre' => 'BOLÍVAR'],
            ['id' => 32, 'provincia_id' => 4, 'codigo' => '0403', 'nombre' => 'ESPEJO'],
            ['id' => 33, 'provincia_id' => 4, 'codigo' => '0404', 'nombre' => 'MIRA'],
            ['id' => 34, 'provincia_id' => 4, 'codigo' => '0405', 'nombre' => 'MONTÚFAR'],
            ['id' => 35, 'provincia_id' => 4, 'codigo' => '0406', 'nombre' => 'SAN PEDRO DE HUACA'],
            ['id' => 36, 'provincia_id' => 5, 'codigo' => '0501', 'nombre' => 'LATACUNGA'],
            ['id' => 37, 'provincia_id' => 5, 'codigo' => '0502', 'nombre' => 'LA MANÁ'],
            ['id' => 38, 'provincia_id' => 5, 'codigo' => '0503', 'nombre' => 'PANGUA'],
            ['id' => 39, 'provincia_id' => 5, 'codigo' => '0504', 'nombre' => 'PUJILÍ'],
            ['id' => 40, 'provincia_id' => 5, 'codigo' => '0505', 'nombre' => 'SALCEDO'],
            ['id' => 41, 'provincia_id' => 5, 'codigo' => '0506', 'nombre' => 'SAQUISILÍ'],
            ['id' => 42, 'provincia_id' => 5, 'codigo' => '0507', 'nombre' => 'SIGCHOS'],
            ['id' => 43, 'provincia_id' => 6, 'codigo' => '0601', 'nombre' => 'RIOBAMBA'],
            ['id' => 44, 'provincia_id' => 6, 'codigo' => '0602', 'nombre' => 'ALAUSÍ'],
            ['id' => 45, 'provincia_id' => 6, 'codigo' => '0603', 'nombre' => 'COLTA'],
            ['id' => 46, 'provincia_id' => 6, 'codigo' => '0604', 'nombre' => 'CHAMBO'],
            ['id' => 47, 'provincia_id' => 6, 'codigo' => '0605', 'nombre' => 'CHUNCHI'],
            ['id' => 48, 'provincia_id' => 6, 'codigo' => '0606', 'nombre' => 'GUAMOTE'],
            ['id' => 49, 'provincia_id' => 6, 'codigo' => '0607', 'nombre' => 'GUANO'],
            ['id' => 50, 'provincia_id' => 6, 'codigo' => '0608', 'nombre' => 'PALLATANGA'],
            ['id' => 51, 'provincia_id' => 6, 'codigo' => '0609', 'nombre' => 'PENIPE'],
            ['id' => 52, 'provincia_id' => 6, 'codigo' => '0610', 'nombre' => 'CUMANDÁ'],
            ['id' => 53, 'provincia_id' => 7, 'codigo' => '0701', 'nombre' => 'MACHALA'],
            ['id' => 54, 'provincia_id' => 7, 'codigo' => '0702', 'nombre' => 'ARENILLAS'],
            ['id' => 55, 'provincia_id' => 7, 'codigo' => '0703', 'nombre' => 'ATAHUALPA'],
            ['id' => 56, 'provincia_id' => 7, 'codigo' => '0704', 'nombre' => 'BALSAS'],
            ['id' => 57, 'provincia_id' => 7, 'codigo' => '0705', 'nombre' => 'CHILLA'],
            ['id' => 58, 'provincia_id' => 7, 'codigo' => '0706', 'nombre' => 'EL GUABO'],
            ['id' => 59, 'provincia_id' => 7, 'codigo' => '0707', 'nombre' => 'HUAQUILLAS'],
            ['id' => 60, 'provincia_id' => 7, 'codigo' => '0708', 'nombre' => 'MARCABELÍ'],
            ['id' => 61, 'provincia_id' => 7, 'codigo' => '0709', 'nombre' => 'PASAJE'],
            ['id' => 62, 'provincia_id' => 7, 'codigo' => '0710', 'nombre' => 'PIÑAS'],
            ['id' => 63, 'provincia_id' => 7, 'codigo' => '0711', 'nombre' => 'PORTOVELO'],
            ['id' => 64, 'provincia_id' => 7, 'codigo' => '0712', 'nombre' => 'SANTA ROSA'],
            ['id' => 65, 'provincia_id' => 7, 'codigo' => '0713', 'nombre' => 'ZARUMA'],
            ['id' => 66, 'provincia_id' => 7, 'codigo' => '0714', 'nombre' => 'LAS LAJAS'],
            ['id' => 67, 'provincia_id' => 8, 'codigo' => '0801', 'nombre' => 'ESMERALDAS'],
            ['id' => 68, 'provincia_id' => 8, 'codigo' => '0802', 'nombre' => 'ELOY ALFARO'],
            ['id' => 69, 'provincia_id' => 8, 'codigo' => '0803', 'nombre' => 'MUISNE'],
            ['id' => 70, 'provincia_id' => 8, 'codigo' => '0804', 'nombre' => 'QUININDÉ'],
            ['id' => 71, 'provincia_id' => 8, 'codigo' => '0805', 'nombre' => 'SAN LORENZO'],
            ['id' => 72, 'provincia_id' => 8, 'codigo' => '0806', 'nombre' => 'ATACAMES'],
            ['id' => 73, 'provincia_id' => 8, 'codigo' => '0807', 'nombre' => 'RIOVERDE'],
            ['id' => 74, 'provincia_id' => 9, 'codigo' => '0901', 'nombre' => 'GUAYAQUIL'],
            ['id' => 75, 'provincia_id' => 9, 'codigo' => '0902', 'nombre' => 'ALFREDO BAQUERIZO MORENO (JUJÁN)'],
            ['id' => 76, 'provincia_id' => 9, 'codigo' => '0903', 'nombre' => 'BALAO'],
            ['id' => 77, 'provincia_id' => 9, 'codigo' => '0904', 'nombre' => 'BALZAR'],
            ['id' => 78, 'provincia_id' => 9, 'codigo' => '0905', 'nombre' => 'COLIMES'],
            ['id' => 79, 'provincia_id' => 9, 'codigo' => '0906', 'nombre' => 'DAULE'],
            ['id' => 80, 'provincia_id' => 9, 'codigo' => '0907', 'nombre' => 'DURÁN'],
            ['id' => 81, 'provincia_id' => 9, 'codigo' => '0908', 'nombre' => 'EL EMPALME'],
            ['id' => 82, 'provincia_id' => 9, 'codigo' => '0909', 'nombre' => 'EL TRIUNFO'],
            ['id' => 83, 'provincia_id' => 9, 'codigo' => '0910', 'nombre' => 'MILAGRO'],
            ['id' => 84, 'provincia_id' => 9, 'codigo' => '0911', 'nombre' => 'NARANJAL'],
            ['id' => 85, 'provincia_id' => 9, 'codigo' => '0912', 'nombre' => 'NARANJITO'],
            ['id' => 86, 'provincia_id' => 9, 'codigo' => '0913', 'nombre' => 'PALESTINA'],
            ['id' => 87, 'provincia_id' => 9, 'codigo' => '0914', 'nombre' => 'PEDRO CARBO'],
            ['id' => 88, 'provincia_id' => 9, 'codigo' => '0916', 'nombre' => 'SAMBORONDÓN'],
            ['id' => 89, 'provincia_id' => 9, 'codigo' => '0918', 'nombre' => 'SANTA LUCÍA'],
            ['id' => 90, 'provincia_id' => 9, 'codigo' => '0919', 'nombre' => 'SALITRE'],
            ['id' => 91, 'provincia_id' => 9, 'codigo' => '0920', 'nombre' => 'SAN JACINTO DE YAGUACHI'],
            ['id' => 92, 'provincia_id' => 9, 'codigo' => '0921', 'nombre' => 'PLAYAS'],
            ['id' => 93, 'provincia_id' => 9, 'codigo' => '0922', 'nombre' => 'SIMÓN BOLÍVAR'],
            ['id' => 94, 'provincia_id' => 9, 'codigo' => '0923', 'nombre' => 'CORONEL MARCELINO MARIDUEÑA'],
            ['id' => 95, 'provincia_id' => 9, 'codigo' => '0924', 'nombre' => 'LOMAS DE SARGENTILLO'],
            ['id' => 96, 'provincia_id' => 9, 'codigo' => '0925', 'nombre' => 'NOBOL'],
            ['id' => 97, 'provincia_id' => 9, 'codigo' => '0927', 'nombre' => 'GENERAL ANTONIO ELIZALDE'],
            ['id' => 98, 'provincia_id' => 9, 'codigo' => '0928', 'nombre' => 'ISIDRO AYORA'],
            ['id' => 99, 'provincia_id' => 10, 'codigo' => '1001', 'nombre' => 'IBARRA'],
            ['id' => 100, 'provincia_id' => 10, 'codigo' => '1002', 'nombre' => 'ANTONIO ANTE'],
            ['id' => 101, 'provincia_id' => 10, 'codigo' => '1003', 'nombre' => 'COTACACHI'],
            ['id' => 102, 'provincia_id' => 10, 'codigo' => '1004', 'nombre' => 'OTAVALO'],
            ['id' => 103, 'provincia_id' => 10, 'codigo' => '1005', 'nombre' => 'PIMAMPIRO'],
            ['id' => 104, 'provincia_id' => 10, 'codigo' => '1006', 'nombre' => 'SAN MIGUEL DE URCUQUÍ'],
            ['id' => 105, 'provincia_id' => 11, 'codigo' => '1101', 'nombre' => 'LOJA'],
            ['id' => 106, 'provincia_id' => 11, 'codigo' => '1102', 'nombre' => 'CALVAS'],
            ['id' => 107, 'provincia_id' => 11, 'codigo' => '1103', 'nombre' => 'CATAMAYO'],
            ['id' => 108, 'provincia_id' => 11, 'codigo' => '1104', 'nombre' => 'CELICA'],
            ['id' => 109, 'provincia_id' => 11, 'codigo' => '1105', 'nombre' => 'CHAGUARPAMBA'],
            ['id' => 110, 'provincia_id' => 11, 'codigo' => '1106', 'nombre' => 'ESPÍNDOLA'],
            ['id' => 111, 'provincia_id' => 11, 'codigo' => '1107', 'nombre' => 'GONZANAMÁ'],
            ['id' => 112, 'provincia_id' => 11, 'codigo' => '1108', 'nombre' => 'MACARÁ'],
            ['id' => 113, 'provincia_id' => 11, 'codigo' => '1109', 'nombre' => 'PALTAS'],
            ['id' => 114, 'provincia_id' => 11, 'codigo' => '1110', 'nombre' => 'PUYANGO'],
            ['id' => 115, 'provincia_id' => 11, 'codigo' => '1111', 'nombre' => 'SARAGURO'],
            ['id' => 116, 'provincia_id' => 11, 'codigo' => '1112', 'nombre' => 'SOZORANGA'],
            ['id' => 117, 'provincia_id' => 11, 'codigo' => '1113', 'nombre' => 'ZAPOTILLO'],
            ['id' => 118, 'provincia_id' => 11, 'codigo' => '1114', 'nombre' => 'PINDAL'],
            ['id' => 119, 'provincia_id' => 11, 'codigo' => '1115', 'nombre' => 'QUILANGA'],
            ['id' => 120, 'provincia_id' => 11, 'codigo' => '1116', 'nombre' => 'OLMEDO'],
            ['id' => 121, 'provincia_id' => 12, 'codigo' => '1201', 'nombre' => 'BABAHOYO'],
            ['id' => 122, 'provincia_id' => 12, 'codigo' => '1202', 'nombre' => 'BABA'],
            ['id' => 123, 'provincia_id' => 12, 'codigo' => '1203', 'nombre' => 'MONTALVO'],
            ['id' => 124, 'provincia_id' => 12, 'codigo' => '1204', 'nombre' => 'PUEBLOVIEJO'],
            ['id' => 125, 'provincia_id' => 12, 'codigo' => '1205', 'nombre' => 'QUEVEDO'],
            ['id' => 126, 'provincia_id' => 12, 'codigo' => '1206', 'nombre' => 'URDANETA'],
            ['id' => 127, 'provincia_id' => 12, 'codigo' => '1207', 'nombre' => 'VENTANAS'],
            ['id' => 128, 'provincia_id' => 12, 'codigo' => '1208', 'nombre' => 'VINCES'],
            ['id' => 129, 'provincia_id' => 12, 'codigo' => '1209', 'nombre' => 'PALENQUE'],
            ['id' => 130, 'provincia_id' => 12, 'codigo' => '1210', 'nombre' => 'BUENA FE'],
            ['id' => 131, 'provincia_id' => 12, 'codigo' => '1211', 'nombre' => 'VALENCIA'],
            ['id' => 132, 'provincia_id' => 12, 'codigo' => '1212', 'nombre' => 'MOCACHE'],
            ['id' => 133, 'provincia_id' => 12, 'codigo' => '1213', 'nombre' => 'QUINSALOMA'],
            ['id' => 134, 'provincia_id' => 13, 'codigo' => '1301', 'nombre' => 'PORTOVIEJO'],
            ['id' => 135, 'provincia_id' => 13, 'codigo' => '1302', 'nombre' => 'BOLÍVAR'],
            ['id' => 136, 'provincia_id' => 13, 'codigo' => '1303', 'nombre' => 'CHONE'],
            ['id' => 137, 'provincia_id' => 13, 'codigo' => '1304', 'nombre' => 'EL CARMEN'],
            ['id' => 138, 'provincia_id' => 13, 'codigo' => '1305', 'nombre' => 'FLAVIO ALFARO'],
            ['id' => 139, 'provincia_id' => 13, 'codigo' => '1306', 'nombre' => 'JIPIJAPA'],
            ['id' => 140, 'provincia_id' => 13, 'codigo' => '1307', 'nombre' => 'JUNÍN'],
            ['id' => 141, 'provincia_id' => 13, 'codigo' => '1308', 'nombre' => 'MANTA'],
            ['id' => 142, 'provincia_id' => 13, 'codigo' => '1309', 'nombre' => 'MONTECRISTI'],
            ['id' => 143, 'provincia_id' => 13, 'codigo' => '1310', 'nombre' => 'PAJÁN'],
            ['id' => 144, 'provincia_id' => 13, 'codigo' => '1311', 'nombre' => 'PICHINCHA'],
            ['id' => 145, 'provincia_id' => 13, 'codigo' => '1312', 'nombre' => 'ROCAFUERTE'],
            ['id' => 146, 'provincia_id' => 13, 'codigo' => '1313', 'nombre' => 'SANTA ANA'],
            ['id' => 147, 'provincia_id' => 13, 'codigo' => '1314', 'nombre' => 'SUCRE'],
            ['id' => 148, 'provincia_id' => 13, 'codigo' => '1315', 'nombre' => 'TOSAGUA'],
            ['id' => 149, 'provincia_id' => 13, 'codigo' => '1316', 'nombre' => '24 DE MAYO'],
            ['id' => 150, 'provincia_id' => 13, 'codigo' => '1317', 'nombre' => 'PEDERNALES'],
            ['id' => 151, 'provincia_id' => 13, 'codigo' => '1318', 'nombre' => 'OLMEDO'],
            ['id' => 152, 'provincia_id' => 13, 'codigo' => '1319', 'nombre' => 'PUERTO LÓPEZ'],
            ['id' => 153, 'provincia_id' => 13, 'codigo' => '1320', 'nombre' => 'JAMA'],
            ['id' => 154, 'provincia_id' => 13, 'codigo' => '1321', 'nombre' => 'JARAMIJÓ'],
            ['id' => 155, 'provincia_id' => 13, 'codigo' => '1322', 'nombre' => 'SAN VICENTE'],
            ['id' => 156, 'provincia_id' => 14, 'codigo' => '1401', 'nombre' => 'MORONA'],
            ['id' => 157, 'provincia_id' => 14, 'codigo' => '1402', 'nombre' => 'GUALAQUIZA'],
            ['id' => 158, 'provincia_id' => 14, 'codigo' => '1403', 'nombre' => 'LIMÓN INDANZA'],
            ['id' => 159, 'provincia_id' => 14, 'codigo' => '1404', 'nombre' => 'PALORA'],
            ['id' => 160, 'provincia_id' => 14, 'codigo' => '1405', 'nombre' => 'SANTIAGO'],
            ['id' => 161, 'provincia_id' => 14, 'codigo' => '1406', 'nombre' => 'SUCÚA'],
            ['id' => 162, 'provincia_id' => 14, 'codigo' => '1407', 'nombre' => 'HUAMBOYA'],
            ['id' => 163, 'provincia_id' => 14, 'codigo' => '1408', 'nombre' => 'SAN JUAN BOSCO'],
            ['id' => 164, 'provincia_id' => 14, 'codigo' => '1409', 'nombre' => 'TAISHA'],
            ['id' => 165, 'provincia_id' => 14, 'codigo' => '1410', 'nombre' => 'LOGROÑO'],
            ['id' => 166, 'provincia_id' => 14, 'codigo' => '1411', 'nombre' => 'PABLO SEXTO'],
            ['id' => 167, 'provincia_id' => 14, 'codigo' => '1412', 'nombre' => 'TIWINTZA'],
            ['id' => 168, 'provincia_id' => 15, 'codigo' => '1501', 'nombre' => 'TENA'],
            ['id' => 169, 'provincia_id' => 15, 'codigo' => '1503', 'nombre' => 'ARCHIDONA'],
            ['id' => 170, 'provincia_id' => 15, 'codigo' => '1504', 'nombre' => 'EL CHACO'],
            ['id' => 171, 'provincia_id' => 15, 'codigo' => '1507', 'nombre' => 'QUIJOS'],
            ['id' => 172, 'provincia_id' => 15, 'codigo' => '1509', 'nombre' => 'CARLOS JULIO AROSEMENA TOLA'],
            ['id' => 173, 'provincia_id' => 16, 'codigo' => '1601', 'nombre' => 'PASTAZA'],
            ['id' => 174, 'provincia_id' => 16, 'codigo' => '1602', 'nombre' => 'MERA'],
            ['id' => 175, 'provincia_id' => 16, 'codigo' => '1603', 'nombre' => 'SANTA CLARA'],
            ['id' => 176, 'provincia_id' => 16, 'codigo' => '1604', 'nombre' => 'ARAJUNO'],
            ['id' => 177, 'provincia_id' => 17, 'codigo' => '1701', 'nombre' => 'DISTRITO METROPOLITANO DE QUITO'],
            ['id' => 178, 'provincia_id' => 17, 'codigo' => '1702', 'nombre' => 'CAYAMBE'],
            ['id' => 179, 'provincia_id' => 17, 'codigo' => '1703', 'nombre' => 'MEJÍA'],
            ['id' => 180, 'provincia_id' => 17, 'codigo' => '1704', 'nombre' => 'PEDRO MONCAYO'],
            ['id' => 181, 'provincia_id' => 17, 'codigo' => '1705', 'nombre' => 'RUMIÑAHUI'],
            ['id' => 182, 'provincia_id' => 17, 'codigo' => '1707', 'nombre' => 'SAN MIGUEL DE LOS BANCOS'],
            ['id' => 183, 'provincia_id' => 17, 'codigo' => '1708', 'nombre' => 'PEDRO VICENTE MALDONADO'],
            ['id' => 184, 'provincia_id' => 17, 'codigo' => '1709', 'nombre' => 'PUERTO QUITO'],
            ['id' => 185, 'provincia_id' => 18, 'codigo' => '1801', 'nombre' => 'AMBATO'],
            ['id' => 186, 'provincia_id' => 18, 'codigo' => '1802', 'nombre' => 'BAÑOS DE AGUA SANTA'],
            ['id' => 187, 'provincia_id' => 18, 'codigo' => '1803', 'nombre' => 'CEVALLOS'],
            ['id' => 188, 'provincia_id' => 18, 'codigo' => '1804', 'nombre' => 'MOCHA'],
            ['id' => 189, 'provincia_id' => 18, 'codigo' => '1805', 'nombre' => 'PATATE'],
            ['id' => 190, 'provincia_id' => 18, 'codigo' => '1806', 'nombre' => 'QUERO'],
            ['id' => 191, 'provincia_id' => 18, 'codigo' => '1807', 'nombre' => 'SAN PEDRO DE PELILEO'],
            ['id' => 192, 'provincia_id' => 18, 'codigo' => '1808', 'nombre' => 'SANTIAGO DE PÍLLARO'],
            ['id' => 193, 'provincia_id' => 18, 'codigo' => '1809', 'nombre' => 'TISALEO'],
            ['id' => 194, 'provincia_id' => 19, 'codigo' => '1901', 'nombre' => 'ZAMORA'],
            ['id' => 195, 'provincia_id' => 19, 'codigo' => '1902', 'nombre' => 'CHINCHIPE'],
            ['id' => 196, 'provincia_id' => 19, 'codigo' => '1903', 'nombre' => 'NANGARITZA'],
            ['id' => 197, 'provincia_id' => 19, 'codigo' => '1904', 'nombre' => 'YACUAMBI'],
            ['id' => 198, 'provincia_id' => 19, 'codigo' => '1905', 'nombre' => 'YANTZAZA'],
            ['id' => 199, 'provincia_id' => 19, 'codigo' => '1906', 'nombre' => 'EL PANGUI'],
            ['id' => 200, 'provincia_id' => 19, 'codigo' => '1907', 'nombre' => 'CENTINELA DEL CÓNDOR'],
            ['id' => 201, 'provincia_id' => 19, 'codigo' => '1908', 'nombre' => 'PALANDA'],
            ['id' => 202, 'provincia_id' => 19, 'codigo' => '1909', 'nombre' => 'PAQUISHA'],
            ['id' => 203, 'provincia_id' => 20, 'codigo' => '2001', 'nombre' => 'SAN CRISTÓBAL'],
            ['id' => 204, 'provincia_id' => 20, 'codigo' => '2002', 'nombre' => 'ISABELA'],
            ['id' => 205, 'provincia_id' => 20, 'codigo' => '2003', 'nombre' => 'SANTA CRUZ'],
            ['id' => 206, 'provincia_id' => 21, 'codigo' => '2101', 'nombre' => 'LAGO AGRIO'],
            ['id' => 207, 'provincia_id' => 21, 'codigo' => '2102', 'nombre' => 'GONZALO PIZARRO'],
            ['id' => 208, 'provincia_id' => 21, 'codigo' => '2103', 'nombre' => 'PUTUMAYO'],
            ['id' => 209, 'provincia_id' => 21, 'codigo' => '2104', 'nombre' => 'SHUSHUFINDI'],
            ['id' => 210, 'provincia_id' => 21, 'codigo' => '2105', 'nombre' => 'SUCUMBÍOS'],
            ['id' => 211, 'provincia_id' => 21, 'codigo' => '2106', 'nombre' => 'CASCALES'],
            ['id' => 212, 'provincia_id' => 21, 'codigo' => '2107', 'nombre' => 'CUYABENO'],
            ['id' => 213, 'provincia_id' => 22, 'codigo' => '2201', 'nombre' => 'FRANCISCO DE ORELLANA'],
            ['id' => 214, 'provincia_id' => 22, 'codigo' => '2202', 'nombre' => 'AGUARICO'],
            ['id' => 215, 'provincia_id' => 22, 'codigo' => '2203', 'nombre' => 'LA JOYA DE LOS SACHAS'],
            ['id' => 216, 'provincia_id' => 22, 'codigo' => '2204', 'nombre' => 'LORETO'],
            ['id' => 217, 'provincia_id' => 23, 'codigo' => '2301', 'nombre' => 'SANTO DOMINGO'],
            ['id' => 218, 'provincia_id' => 23, 'codigo' => '2302', 'nombre' => 'LA CONCORDIA'],
            ['id' => 219, 'provincia_id' => 24, 'codigo' => '2401', 'nombre' => 'SANTA ELENA'],
            ['id' => 220, 'provincia_id' => 24, 'codigo' => '2402', 'nombre' => 'LA LIBERTAD'],
            ['id' => 221, 'provincia_id' => 24, 'codigo' => '2403', 'nombre' => 'SALINAS'],
            ['id' => 222, 'provincia_id' => 25, 'codigo' => '2501', 'nombre' => 'LAS GOLONDRINAS'],
            ['id' => 223, 'provincia_id' => 25, 'codigo' => '2502', 'nombre' => 'MANGA DEL CURA'],
            ['id' => 224, 'provincia_id' => 25, 'codigo' => '2503', 'nombre' => 'EL PIEDRERO'],

        ]);
    }
}
