services:
  - type: web
    name: backend-laravel
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: CACHE_DRIVER
        value: file
