POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"

}

### Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 2|M8Ong9tnbFnZQ1YGaW4a4r5PaBipRzkNWAHVIjti337eb3c0


### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 3|DJIfTUEuH7TE2KIIcspdUYOQ0dpbfpKws7oxuTcPa4b2272a